/*
 *	java_lang_Object.c
 *
 *	Copyright (c) 2008 CSIRO, Delft University of Technology.
 *
 *	This file is part of Darjeeling.
 *
 *	Darjeeling is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 3 of the License, or
 *	(at your option) any later version.
 *
 *	Darjeeling is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with Darjeeling.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stddef.h>

#include "execution.h"
#include "vmthread.h"
#include "vm.h"

#include "pointerwidth.h"

// generated by the infuser
#include "jlib_base.h"

// void java.lang.Object.wait(int)
void java_lang_Object_void_wait_int()
{
	dj_object * object = (dj_object*)REF_TO_VOIDP(dj_exec_stackPopRef());
	int32_t timeOut = dj_exec_stackPopInt();

	dj_thread * thread = dj_exec_getCurrentThread();

	dj_thread_wait(thread, object, timeOut);
	dj_exec_breakExecution();
}

// void java.lang.Object.wait()
void java_lang_Object_void_wait()
{
	dj_object * object = (dj_object*)REF_TO_VOIDP(dj_exec_stackPopRef());
	dj_thread * thread = dj_exec_getCurrentThread();

	dj_thread_wait(thread, object, 0);
	dj_exec_breakExecution();
}

// void java.lang.Object.notify()
void java_lang_Object_void_notify()
{
	dj_object * object = (dj_object*)REF_TO_VOIDP(dj_exec_stackPopRef());

	// make sure the thread owns the lock
	// TODO implement this check

	dj_vm_notify(dj_exec_getVM(), object, false);
}

// void java.lang.Object.notifyAll()
void java_lang_Object_void_notifyAll()
{
	dj_object * object = (dj_object*)REF_TO_VOIDP(dj_exec_stackPopRef());
	dj_vm_notify(dj_exec_getVM(), object, false);
}
