/*
 * javax_darjeeling_vm_Infusion.c
 * 
 * Copyright (c) 2008-2010 CSIRO, Delft University of Technology.
 * 
 * This file is part of Darjeeling.
 * 
 * Darjeeling is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Darjeeling is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with Darjeeling.  If not, see <http://www.gnu.org/licenses/>.
 */
 

#include "execution.h"
#include "global_id.h"
#include "debug.h"
#include "heap.h"
#include "panic.h"
#include "array.h"

// generated by the infuser
#include "jlib_base.h"

// short javax.darjeeling.vm.Infusion.getInfusionCount()
void javax_darjeeling_vm_Infusion_short_getInfusionCount()
{
	dj_exec_stackPushShort(dj_vm_countInfusions(dj_exec_getVM()));
}

// java.lang.Object javax.darjeeling.vm.Infusion._getInfusion(short)
void javax_darjeeling_vm_Infusion_java_lang_Object__getInfusion_short()
{
	int16_t index = dj_exec_stackPopShort();

	// check for array out of bounds, just to be sure :3
	if (index<0||index>dj_vm_countInfusions(dj_exec_getVM()))
		dj_exec_createAndThrow(BASE_CDEF_java_lang_IndexOutOfBoundsException);

	dj_exec_stackPushRef(VOIDP_TO_REF(dj_vm_getInfusion(dj_exec_getVM(), index)));
}

// char[] javax.darjeeling.vm.Infusion._getName(java.lang.Object)
void javax_darjeeling_vm_Infusion_char____getName_java_lang_Object()
{
	uint16_t count;

	dj_infusion * infusion = (dj_infusion *)REF_TO_VOIDP(dj_exec_stackPopRef());

	// get infusion name (in program memory)
	dj_di_pointer name = dj_di_header_getInfusionName(infusion->header);

	// get the length of the name string
	for (count=0; dj_di_getU8(name+count) != 0; count++);

	// create charArray
	dj_int_array * ret = dj_int_array_create(T_CHAR, count);

	if (ret==NULL)
	{
		dj_exec_createAndThrow(BASE_CDEF_java_lang_OutOfMemoryError);
		return;
	}

	// copy the infusion name into the string
	for (count=0; dj_di_getU8(name+count) != 0; count++)
		ret->data.bytes[count] = dj_di_getU8(name+count);

	dj_exec_stackPushRef(VOIDP_TO_REF(ret));
}


// short javax.darjeeling.vm.Infusion._getImportedInfusionCount(java.lang.Object)
void javax_darjeeling_vm_Infusion_short__getImportedInfusionCount_java_lang_Object()
{
	dj_infusion * infusion = (dj_infusion *)REF_TO_VOIDP(dj_exec_stackPopRef());
	dj_exec_stackPushShort(infusion->nr_referenced_infusions);
}


// java.lang.Object javax.darjeeling.vm.Infusion._getImportedInfusion(java.lang.Object, short)
void javax_darjeeling_vm_Infusion_java_lang_Object__getImportedInfusion_java_lang_Object_short()
{
	int16_t index = dj_exec_stackPopShort();
	dj_infusion * infusion = (dj_infusion *)REF_TO_VOIDP(dj_exec_stackPopRef());

	// check for array out of bounds, just to be sure :3
	if (index<0||index>infusion->nr_referenced_infusions)
		dj_exec_createAndThrow(BASE_CDEF_java_lang_IndexOutOfBoundsException);

	dj_exec_stackPushRef(VOIDP_TO_REF(infusion->referencedInfusions[index]));
}

// void javax.darjeeling.vm.Infusion._unload(java.lang.Object)
void javax_darjeeling_vm_Infusion_void__unload_java_lang_Object()
{
	dj_vm * vm = dj_exec_getVM();
	dj_infusion * infusion = (dj_infusion *)REF_TO_VOIDP(dj_exec_stackPopRef());

	// check for dependencies
	if (!dj_vm_safeToUnload(vm, infusion)||dj_vm_getSystemInfusion(vm)==infusion)
	{
		dj_exec_createAndThrow(BASE_CDEF_javax_darjeeling_vm_InfusionUnloadDependencyException);
		return;
	}

	// unload the infusion
	dj_vm_unloadInfusion(vm, infusion);

	// break execution if the thread that is currently executing has been terminated
	if (dj_exec_getCurrentThread()->status==THREADSTATUS_FINISHED)
		dj_exec_breakExecution();

}
