#include <stddef.h>

#include "common/execution/execution.h"
#include "common/global_id.h"
#include "common/debug.h"
#include "common/heap/heap.h"
#include "common/djtimer.h"

#include "pointerwidth.h"

// generated by the infuser
#include "base_definitions.h"


// void java.lang.Runtime.exitInternal(int)
void java_lang_Runtime_void_exit_int()
{
	// no exit implemented
}

// int java.lang.Runtime.freeMemory()
void java_lang_Runtime_int_freeMemory()
{
	dj_exec_stackPushInt(dj_mem_getFree());
}


// int java.lang.Runtime.totalMemory()
void java_lang_Runtime_int_totalMemory()
{
	dj_exec_stackPushInt(dj_mem_getSize());
}


// void java.lang.Runtime.gc()
void java_lang_Runtime_void_gc()
{
	dj_mem_gc();
}

